# Generated by Django 4.0.4 on 2022-05-24 21:45

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessages',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='privatemessages',
            name='sender',
        ),
        migrations.CreateModel(
            name='PrivateChatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('receiver', models.ForeignKey(on_delete=models.SET(chat.models.get_User), related_name='receiver', to='chat.userprofile')),
                ('sender', models.ForeignKey(on_delete=models.SET(chat.models.get_User), related_name='sender', to='chat.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='privatemessages',
            name='privateChatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.privatechatroom'),
        ),
    ]
