# Generated by Django 4.0.4 on 2022-05-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_privatemessages_privatechatroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedprivatemessages',
            name='srcMessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.privatemessages'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languageKey',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
